
//收藏
export const GET_COLLECTION='GET_COLLECTION';
export const ADD_COLLECTION='ADD_COLLECTION';
export const REMOVE_COLLECTION='REMOVE_COLLECTION';
//订阅
export const GET_SUBSCRIBE='GET_SUBSCRIBE';
export const ADD_SUBSCRIBE='ADD_SUBSCRIBE';
export const REMOVE_SUBSCRIBE='REMOVE_SUBSCRIBE';
//点赞
export const GET_THUM='GET_THUM';
export const ADD_THUM='ADD_THUM';
export const REMOVE_THUM='REMOVE_THUM';
